from . import student_details
from . import class_details
from . import teacher_details
from . import facility_details
from . import attendance_details
from . import subject_details
from . import exam_details
from . import result_details
from . import res_config_settings
